Repository atc0005/query-meta, pull requests merged in 2021-06, with the labels that each got.

#21 New NearFieldBadgeID record field to handle new card scanning
  cmd/qm/main.go
  contrib/qm/config.example.toml
  internal/meta/meta.go
  internal/meta/types.go
Labels: SQL, enhancement

#23 Hide config file specific settings from CLI
  internal/config/types.go
Labels: bug, config

#24 Add config file parsing tests
  cmd/qm/main_test.go
Labels: config, enhancement, tests

#25 Update CHANGELOG for v0.2.0 release
  CHANGELOG.md
Labels: changelog

#29 Add "canary" Dockerfile, Dependabot monitoring
  .github/dependabot.yml
  .github/workflows/lint-docker-files.yml
  dependabot/docker/go/Dockerfile
Labels: CI, dependencies, enhancement
